# Generated by Django 5.0.6 on 2024-05-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_app', '0002_alter_highchartdata_labels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highchartdata',
            name='chart_type',
            field=models.CharField(choices=[('line', 'Line'), ('column', 'Column'), ('pie', 'Pie')], default='line', max_length=10),
        ),
    ]
