# Generated by Django 5.0.6 on 2024-05-28 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_app', '0003_highchartdata_chart_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='highchartdata',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='highchartdata',
            name='values',
        ),
        migrations.CreateModel(
            name='ChartLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='label', max_length=255)),
                ('highchart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='json_app.highchartdata')),
            ],
        ),
        migrations.CreateModel(
            name='ChartValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('highchart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='json_app.highchartdata')),
            ],
        ),
        migrations.AddField(
            model_name='highchartdata',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='json_app.theme'),
        ),
    ]
