# Generated by Django 5.0.6 on 2024-06-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_app', '0005_remove_chartvalue_highchart_highchartdata_labels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highchartdata',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='highchartdata',
            name='chart_type',
            field=models.CharField(choices=[('line', 'Série'), ('column', 'Histogramme'), ('pie', 'Camembert')], default='line', max_length=10),
        ),
    ]
