# Generated by Django 5.0.6 on 2024-06-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('json_app', '0007_highchartdata_pie_value_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highchartdata',
            name='pie_value_type',
        ),
    ]
