# Generated by Django 5.0.6 on 2024-06-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_app', '0008_remove_highchartdata_pie_value_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highchartdata',
            name='chart_type',
            field=models.CharField(choices=[('line', 'Série'), ('column', 'Histogramme'), ('pie', 'Camembert'), ('spline', 'spline')], default='line', max_length=10),
        ),
    ]
