# Generated by Django 5.0.6 on 2024-06-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_app', '0011_alter_highchartdata_chart_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='highchartdata',
            name='x_axis_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='highchartdata',
            name='y_axis_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
