# Generated by Django 5.0.6 on 2024-06-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_app', '0012_highchartdata_x_axis_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highchartdata',
            name='legend_align',
            field=models.CharField(choices=[('left', 'Gauche'), ('center', 'Centre'), ('right', 'Droite')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='highchartdata',
            name='legend_layout',
            field=models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', max_length=10),
        ),
        migrations.AddField(
            model_name='highchartdata',
            name='legend_position',
            field=models.CharField(choices=[('top', 'Haut'), ('bottom', 'Bas')], default='top', max_length=10),
        ),
        migrations.AddField(
            model_name='highchartdata',
            name='show_legend',
            field=models.BooleanField(default=True),
        ),
    ]
