# Generated by Django 5.0.6 on 2024-06-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('json_app', '0013_highchartdata_legend_align_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highchartdata',
            name='legend_align',
        ),
    ]
