# Generated by Django 4.1.7 on 2025-04-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_app', '0015_remove_highchartdata_legend_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highchartdata',
            name='height',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='highchartdata',
            name='pos_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='highchartdata',
            name='pos_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='highchartdata',
            name='width',
            field=models.IntegerField(default=6),
        ),
    ]
